### PR TITLE
Issue 11 (navigation)

### PR DESCRIPTION
**Pull request by ezekohon**
added conditional rendering for Poll Overview and Create Poll navbar items. Is this okay?

### CODE REVIEW

**Comment by markusphil** [comment]
Thank you for your work! :blush: It's a good idea but there is one major drawback. The check won't be able to react on actual changes in the user data, since it is only asigned on the first render of the Menu. The userdata is already available in the VueX store. You can see the state in  `store/modules/user.js`. You can use this state as a computed property in your component.

See https://vuex.vuejs.org/guide/state.html for documentation.

When you get the state from the store, you also could check if a `uid` exists and show/hide the login & logout buttons 😊

**Comment by ezekohon** [comment]
Thanks for the feedback. I'm still learning the framework so this really helps me!!

**Comment by markusphil** [comment]
@ezekohon I'm glad to help you with that! 😊 I started learning vue with this project too, and there are still many aspects that I have to learn.

Maybe you can update your pr so that it uses the store's data and then I'll merge it to the master?

**Comment by ezekohon** [comment]
Made a commit! Please check if now I got it right. I'm not sure if using that getter for the userExists is the right way.

**Comment by markusphil** [comment]
Oh great! 😊 So the way you set up the getter is good, but we don't need it here. Firebase will handle the user authentication and once there is an id the user exists.

This list is actually just for displaying all existing users to the frontend. And it is pretty confusing that i put in the user module where all other state is related to the active user. (It was just the quickest way to set up the userlist, and I really need to refactor it)!

**Comment by markusphil** [comment]
There is still one problem with the default behavior of the bulma `navbar-burger` : it only appears on smaller viewports. But that should be easy to fix via css. You could also adjust the styling to use scss variables for colors (ether form the `_variables.scss` file or from bulma) if you want to work on further improvements.

**Comment by ezekohon** [comment]
Shouldn't that be the correct behavior for the navbar? Hamburger on mobile and normal navbar on desktop? I'll commit the roles thing in this PR and then I'll handle the transition in another so it won't get mixed up.

**Comment by markusphil** [comment]
We'll yes it is expected behavior for a navbar. But with the transition set up the links weren't shown on larger viewports.

Actually I didn't had a navbar in mind for the navigation but rather a side menu like this one: https://codepen.io/james_zedd/pen/ZKVZWp. The idea was that it shouldn't take much space on the admin dashboard and that you initially only see a menu button (that's what i meant with "hidden by default").

If you like to continue working on the navigation I'd encourage you to rework it in this direction. You actually do not need to use any bulma classes for it, but could use there grid if you like to. If you show and hide the whole menu, the transition setup should be way easier though!

Still I  really appreciate the work you've put into the navbar so far. It is a great improvement! 😊

**Pull request merged**
